format = """
[](fg:#9A348E bg:transparent)\
$os\
$hostname\
[](fg:#9A348E bg:#DA627D)\
$shlvl\
$nix_shell\
[](fg:#DA627D bg:#33658A)\
$directory\
[](fg:#33658A bg:#FCA17D)\
${custom.git_server}\
$git_branch\
$git_commit\
$git_state\
$git_metrics\
$git_status\
[](fg:#FCA17D bg:#86BBD8)\
$container\
$docker_context\
$helm\
$kubernetes\
$terraform\
[ ](fg:#86BBD8 bg:transparent)\
"""

# Handy format strings for debugging, add to the beginning of the appropriate
# section of the prompt above (without the leading '# ').
# [ Remote ](bg:#DA627D)\
# [ Lang Environment ](fg:#202020 bg:#86BBD8)\
# [ Docker Context ](bg:#9A348E)\

# Get editor completions based on the config schema
'$schema' = 'https://starship.rs/config-schema.json'

# Disables the custom module
[custom]
disabled = false

[line_break]
disabled = true

# You can also replace your username with a neat symbol like   or disable this
# and use the os module below
[username]
show_always = true
style_user = "fg:#EEEEEE bg:#9A348E"
style_root = "fg:#EE0000 bg:#9A348E"
format = '[$user]($style)'
disabled = false

# An alternative to the username module which displays a symbol that
# represents the current operating system
[os]
format = '[$symbol ]($style)'
style = "fg:#EEEEEE bg:#9A348E"
disabled = false

# redefine OS emojis without trailing spaces, ugh
[os.symbols]
Arch = ""
CentOS = ""
Debian = ""
Fedora = ""
FreeBSD = ""
Linux = ""
Macos = "󰀵"
Mint = ""
NixOS = ""
OpenBSD = ""
openSUSE = ""
SUSE = ""
Redhat = ""
RedHatEnterprise = ""
Unknown = "Unknown OS"
Ubuntu = ""
Windows = ""

[shlvl]
disabled = false
format='[ SHLVL: $shlvl ]($style)'
style = "fg:#EEEEEE bg:#DA627D"

[hostname]
format='[$ssh_symbol$hostname ]($style)'
# trim_at='-'
trim_at='.'
ssh_only = false
ssh_symbol='🌏 '
style = "fg:#EEEEEE bg:#9A348E"
disabled = false

[nix_shell]
symbol='❄️'
style = "bg:#DA627D"
heuristic = true
format = '[$symbol $name ]($style)'
disabled = true

[directory]
style = "bg:#33658A"
format = "[$path]($style)[$lock_symbol]($lock_style)[ ]($style)"
fish_style_pwd_dir_length = 1
truncation_length = 3
# truncation_symbol = "…/"

# FIXME: need to wait for 1.17 release for this, currently in nixos-unstable
# [direnv]
# disabled = false
# format = '[ $symbol ]($style)'
# style = "bg:#33658A"

#######################################################################
# Git

[custom.git_server]
#disabled = true
description = "Display symbol for remote Git server"
command = """
GIT_REMOTE=$(command git ls-remote --get-url 2> /dev/null)
if [[ "$GIT_REMOTE" =~ "github" ]]; then
    GIT_REMOTE_SYMBOL=" "
elif [[ "$GIT_REMOTE" =~ "gitlab" ]]; then
    GIT_REMOTE_SYMBOL=" "
elif [[ "$GIT_REMOTE" =~ "bitbucket" ]]; then
    GIT_REMOTE_SYMBOL=" "
elif [[ "$GIT_REMOTE" =~ "git" ]]; then
    GIT_REMOTE_SYMBOL=" "
else
    GIT_REMOTE_SYMBOL=" "
fi
echo "$GIT_REMOTE_SYMBOL "
"""
when = 'git rev-parse --is-inside-work-tree 2> /dev/null'
style = "fg:#202020 bg:#FCA17D"
# style = "white"
format = '[$output ]($style)'

[custom.git_scope]
disabled = true
command = '''
printf "%s (%s)" \
  "$(if [ -n "$GIT_AUTHOR_EMAIL" ]; then echo "$GIT_AUTHOR_EMAIL"; else git config user.email; fi)" \
  "$(if [ -n "$GIT_AUTHOR_NAME" ]; then echo "$GIT_AUTHOR_NAME"; else git config user.name; fi)"
'''
description = 'The currently configured Git user.{email,name}'
format = '[$output ]($style)'
style = "fg:#202020 bg:#FCA17D"
# style = 'blue bold'
when = 'git rev-parse --is-inside-work-tree'

[custom.git_last_commit]
# disabled = true
description = "Display last commit hash and message"
command = "git show -s --format='%h \"%s\"'"
when = 'git rev-parse --is-inside-work-tree 2> /dev/null'
style = "fg:#202020 bg:#FCA17D"
#style = "bright-yellow bold"
format = '[$output ]($style)'

[git_branch]
format = '[\[$symbol$branch\]]($style)'
style = "fg:#202020 bg:#FCA17D"
symbol = ''
truncation_length = 16
truncation_symbol = '…'

[git_commit]
commit_hash_length = 8
style = "fg:#202020 bg:#FCA17D"
tag_symbol = '🔖 '
disabled = false

[git_state]
format = '[\[\($state( $progress_current of $progress_total)\)\]]($style)'
style = "fg:#202020 bg:#FCA17D"

[git_status]
conflicted = "⚔️"
ahead = "💨${count}"
behind = "🐢${count}"
diverged = "🔱 💨${ahead_count} 🐢${behind_count}"
untracked = "🛤️${count}"
stashed = "📦"
modified = "📝${count}"
staged = "🗃️${count}"
renamed = "📛${count}"
deleted = "🗑️${count}"
style = "fg:#202020 bg:#FCA17D"
format = '[\[$all_status$ahead_behind\] ]($style)'

#######################################################################
# Virtualization

[container]
format = '[ $symbol($name) ]($style)'
style = "fg:#000000 bg:#86BBD8"

[docker_context]
format = '[ $symbol($context) ]($style)'
style = "fg:#000000 bg:#86BBD8"

[helm]
#disabled = false
format = '[$symbol($version) ]($style)'
style = "fg:#000000 bg:#86BBD8"

[kubernetes]
#disabled = false
format = '[ $symbol$context(\($namespace\)) ]($style)'
style = "fg:#000000 bg:#86BBD8"

[terraform]
#disabled = false
format = '[$symbol$version ]($style)'
style = "fg:#000000 bg:#86BBD8"
symbol = "💠"
version_format = "${major}.${minor}"

# [custom.nixlang]
# command = "nix --version | awk '{ print $3 }'"
# detect_extensions = ['nix']
# format = '[ $symbol ]($style)'
# style = "fg:#000000 bg:#86BBD8"
# symbol='❄️'

#######################################################################
# Color Palettes

[palettes.solarized_dark]
# Ordered from darker to lighter
base03    = "#002b36"   # background tones
base02    = "#073642"
base01    = "#586e75"   # content tones
base00    = "#657b83"
base0     = "#839496"
base1     = "#93a1a1"
base2     = "#eee8d5"   # background tones
base3     = "#fdf6e3"
# Accent colors
blue      = "#268bd2"   
cyan      = "#2aa198"
green     = "#859900"
magenta   = "#d33682"
orange    = "#cb4b16"
red       = "#dc322f"
violet    = "#6c71c4"
yellow    = "#b58900"
# Semantic Colors
user_section_fg      = "#6c71c4" # yellow
user_section_bg      = "#002b36" # base03
shell_section_fg     = "#6c71c4" # violet
shell_section_bg     = "#fdf6e3" # base3
directory_section_fg = "#cb4b16" # orange
directory_section_bg = "#073642" # base02
git_section_fg       = "#d33682" # magenta
git_section_bg       = "#eee8d5" # base2
language_section_fg  = "#2aa198" # cyan
language_section_bg  = "#586e75" # base01


