format = """
[](fg:#9A348E bg:transparent)\
$os\
[](fg:#9A348E bg:#DA627D)\
$shlvl\
$hostname\
$nix_shell\
[](fg:#DA627D bg:#33658A)\
$directory\
[](fg:#33658A bg:#FCA17D)\
$git_branch\
$git_status\
[](fg:#FCA17D bg:#86BBD8)\
$container\
$golang\
$helm\
$java\
$kotlin\
$kubernetes\
${custom.nixlang}\
$nodejs\
$ruby\
$rust\
$swift\
$vagrant\
[ ](fg:#86BBD8 bg:transparent)\
"""

# Handy format strings for debugging, add to the beginning of the appropriate
# section of the prompt above (without the leading '# ').
# [ Remote ](bg:#DA627D)\
# [ Lang Environment ](fg:#202020 bg:#86BBD8)\
# [ Docker Context ](bg:#9A348E)\

# Get editor completions based on the config schema
'$schema' = 'https://starship.rs/config-schema.json'

# Disables the custom module
[custom]
disabled = false

[line_break]
disabled = true

# You can also replace your username with a neat symbol like   or disable this
# and use the os module below
[username]
show_always = true
style_user = "fg:#EEEEEE bg:#9A348E"
style_root = "fg:#EE0000 bg:#9A348E"
format = '[$user]($style)'
disabled = false

# An alternative to the username module which displays a symbol that
# represents the current operating system
[os]
format = '[ $symbol ]($style)'
style = "fg:#EEEEEE bg:#9A348E"
disabled = false

# redefine OS emojis without trailing spaces, ugh
[os.symbols]
Arch = "🎗️ Arch"
CentOS = "💠 CentOS"
Debian = "🌀 Debian"
Fedora = "🎩 Fedora"
FreeBSD = "😈 FreeBSD"
Linux = "🐧 Linux"
Macos = " macOS"
Mint = "🌿 Mint"
NixOS = "❄️ NixOS"
OpenBSD = "🐡 OpenBSD"
openSUSE = "🦎 openSUSE"
Redhat = "🎩 Redhat"
RedHatEnterprise = "🎩 RedHatEnterprise"
SUSE = "🦎 SUSE"
Unknown = "❓ Unknown"
Ubuntu = "🎯 Ubuntu"
Windows = " Windows"

[shlvl]
disabled = false
format='[ SHLVL: $shlvl ]($style)'
style = "fg:#EEEEEE bg:#DA627D"

[hostname]
format='[$ssh_symbol$hostname ]($style)'
trim_at='.'
ssh_symbol='🌏'
style = "bg:#DA627D"
disabled = false

[nix_shell]
symbol='❄️'
style = "bg:#DA627D"
heuristic = true
format = '[$symbol $name ]($style)'
disabled = true

[directory]
style = "bg:#33658A"
format = "[ $path ]($style)"
truncation_length = 3
truncation_symbol = "…/"

# Here is how you can shorten some long paths by text replacement
# similar to mapped_locations in Oh My Posh:
[directory.substitutions]
"~" = "\uf7dd "
"~/Development" = "\ue5fb "
"~/Downloads" = "  "
"Documents" = "\U000f19f6 "
"Music" = "  "
"Pictures" = "  "
# Keep in mind that the order matters. For example:
# "Important Documents " = "\U000f19f6 "
# will not be replaced, because "Documents" was already substituted before.
# So either put "Important Documents" before "Documents" or use the substituted version:
# "Important \U000f19f6 " = "\U000f19f6 "

[git_branch]
style = "fg:#202020 bg:#FCA17D"
format = '[ $symbol($branch) ]($style)'

[git_status]
style = "fg:#202020 bg:#FCA17D"
format = '[$all_status$ahead_behind ]($style)'

[time]
disabled = true
time_format = "%R" # Hour:Minute Format
style = "bg:#33658A"
format = '[ $time ]($style)'

################################################################

[container]
format = '[ $symbol($name) ]($style)'
style = "fg:#000000 bg:#86BBD8"

[docker_context]
format = '[ $symbol($context) ]($style)'
style = "fg:#000000 bg:#86BBD8"

[golang]
format = '[ $symbol ]($style)'
style = "fg:#000000 bg:#86BBD8"

[helm]
format = '[ $symbol ]($style)'
style = "fg:#000000 bg:#86BBD8"

[java]
format = '[ $symbol ]($style)'
style = "fg:#000000 bg:#86BBD8"
symbol = " "

[kotlin]
format = '[ $symbol ]($style)'
style = "fg:#000000 bg:#86BBD8"

[kubernetes]
format = '[ $symbol$context(\($namespace\)) ]($style)'
#disabled = false
style = "fg:#000000 bg:#86BBD8"

[nodejs]
format = '[ $symbol ]($style)'
style = "fg:#FFE53D bg:#86BBD8"
symbol = ""

[ruby]
format = '[ $symbol ]($style)'
style = "fg:#E0115F bg:#86BBD8"
symbol = ""

[rust]
format = '[ $symbol ]($style)'
style = "fg:#000000 bg:#86BBD8"

[swift]
format = '[ $symbol ]($style)'
style = "fg:#000000 bg:#86BBD8"

[custom.nixlang]
# command = "nix --version | sed -e 's/nix (Nix) //g'"
detect_extensions = ['nix']
format = '[ $symbol ]($style)'
style = "fg:#000000 bg:#86BBD8"
symbol='❄️'

#######################################################################

[palettes.solarized_dark]
# Ordered from darker to lighter
base03    = "#002b36"   # background tones
base02    = "#073642"
base01    = "#586e75"   # content tones
base00    = "#657b83"
base0     = "#839496"
base1     = "#93a1a1"
base2     = "#eee8d5"   # background tones
base3     = "#fdf6e3"
# Accent colors
blue      = "#268bd2"   
cyan      = "#2aa198"
green     = "#859900"
magenta   = "#d33682"
orange    = "#cb4b16"
red       = "#dc322f"
violet    = "#6c71c4"
yellow    = "#b58900"
# Semantic Colors
user_section_fg      = "#6c71c4" # yellow
user_section_bg      = "#002b36" # base03
shell_section_fg     = "#6c71c4" # violet
shell_section_bg     = "#fdf6e3" # base3
directory_section_fg = "#cb4b16" # orange
directory_section_bg = "#073642" # base02
git_section_fg       = "#d33682" # magenta
git_section_bg       = "#eee8d5" # base2
language_section_fg  = "#2aa198" # cyan
language_section_bg  = "#586e75" # base01


