format = """
[](fg:#9A348E)\
$os\
$username\
[](fg:#9A348E bg:#DA627D)\
$shlvl\
$hostname\
$nix_shell\
[](fg:#DA627D bg:#33658A)\
$directory\
[](fg:#33658A bg:#FCA17D)\
$git_branch\
$git_status\
[](fg:#FCA17D bg:#86BBD8)\
$c\
$golang\
$java\
$nodejs\
$ruby\
$rust\
[](fg:#86BBD8 bg:#9A348E)\
$docker_context\
[](fg:#9A348E)\
"""

# Handy format strings for debugging, add to the beginning of the appropriate
# section of the prompt above.
# [ Remote ](bg:#DA627D)\
# [ Lang Environment ](fg:#202020 bg:#86BBD8)\
# [ Docker Context ](bg:#9A348E)\

# Get editor completions based on the config schema
"$schema" = 'https://starship.rs/config-schema.json'

# Disable the blank line at the start of the prompt
# add_newline = false

# An alternative to the username module which displays a symbol that
# represents the current operating system
[os]
style = "bg:#9A348E"
disabled = true # Disabled by default

# You can also replace your username with a neat symbol like   or disable this
# and use the os module below
[username]
show_always = true
style_user = "bg:#9A348E"
style_root = "bg:#9A348E"
format = '[ $user ]($style)'
disabled = false

[shlvl]
style = "fg:#202020 bg:#33658A"
disabled = false

[hostname]
format='[$ssh_symbol$hostname]($style) '
trim_at='.'
ssh_symbol='🌏'
style = "fg:#202020 bg:#33658A"
disabled = false

[nix_shell]
symbol='❄️'
style = "fg:#202020 bg:#33658A"
format = '[ $symbol $name $state ]($style)'
disabled = false

[directory]
style = "bg:#33658A"
format = "[ $path ]($style)"
truncation_length = 3
truncation_symbol = "…/"

# Here is how you can shorten some long paths by text replacement
# similar to mapped_locations in Oh My Posh:
[directory.substitutions]
"~/Development" = "󰦬 "
"~/Downloads" = " "
"Documents" = "󰈙 "
"Music" = " "
"Pictures" = " "
# Keep in mind that the order matters. For example:
# "Important Documents" = " 󰈙 "
# will not be replaced, because "Documents" was already substituted before.
# So either put "Important Documents" before "Documents" or use the substituted version:
# "Important 󰈙 " = " 󰈙 "

[docker_context]
style = "bg:#06969A"
format = '[ $symbol$context ]($style)'

[git_branch]
style = "fg:#202020 bg:#FCA17D"
format = '[ $symbol($branch) ]($style)'

[git_status]
style = "fg:#202020 bg:#FCA17D"
format = '[ $all_status$ahead_behind ]($style)'

[time]
disabled = true
time_format = "%R" # Hour:Minute Format
style = "bg:#33658A"
format = '[ $time ]($style)'

################################################################

[c]
style = "fg:#202020 bg:#86BBD8"
format = '[ $symbol($version) ]($style)'

[elixir]
style = "fg:#202020 bg:#86BBD8"
format = '[ $symbol($version) ]($style)'

[elm]
style = "fg:#202020 bg:#86BBD8"
format = '[ $symbol($version) ]($style)'

[golang]
style = "fg:#202020 bg:#86BBD8"
format = '[ $symbol($version) ]($style)'

[gradle]
style = "fg:#202020 bg:#86BBD8"
format = '[ $symbol($version) ]($style)'

[haskell]
style = "fg:#202020 bg:#86BBD8"
format = '[ $symbol($version) ]($style)'

[java]
symbol = " "
style = "fg:#202020 bg:#86BBD8"
format = '[ $symbol($version) ]($style)'

[julia]
symbol = " "
style = "fg:#202020 bg:#86BBD8"
format = '[ $symbol($version) ]($style)'

[nodejs]
symbol = ""
style = "fg:#202020 bg:#86BBD8"
format = '[ $symbol($version) ]($style)'

[nim]
style = "fg:#202020 bg:#86BBD8"
format = '[ $symbol($version) ]($style)'

[ruby]
style = "fg:#202020 bg:#86BBD8"
format = '[ $symbol($version) ]($style)'

[rust]
style = "fg:#202020 bg:#86BBD8"
format = '[ $symbol($version) ]($style)'

[scala]
style = "fg:#202020 bg:#86BBD8"
format = '[ $symbol($version) ]($style)'
