name: Bump flake.lock

on:
  schedule:
    - cron: "0 6 * * *"

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      # Give the default GITHUB_TOKEN write permission to commit and push the
      # added or changed files to the repository.
      contents: write
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - uses: cachix/install-nix-action@v20

      - run: nix flake update --accept-flake-config

      - name: Run Statix Lint
        run: statix fix

      - name: Run Nix Formatter
        run: nix fmt

      - name: Nix Flake Checker
        # You may pin to the exact commit or the version.
        # uses: DeterminateSystems/flake-checker-action@4b90f9fc724969ff153fe1803460917c84fe00a3
        uses: DeterminateSystems/flake-checker-action@v5

      - uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: Bump flake.lock and run linter/formatter
          branch: main
          commit_options: '--no-verify --signoff'
          file_pattern: flake.lock
          commit_user_name: Nix Config Flake Update Action # defaults to "GitHub Actions"
          commit_user_email: github-actions-bot@cattivi.com # defaults to "actions@github.com"
          commit_author: Flake Bot <actions@github.com> # defaults to author of the commit that triggered the run
          skip_dirty_check: false    
          skip_fetch: true
